### ISSUE TITLE
java.lang.IncompatibleClassChangeError in version 1.0.9

### ISSUE THREAD

**Issue by antoon-r** [scapegoat-scala/sbt-scapegoat#71]
Hi. I have multi-module sbt project with single module.

My environment:
* sbt.version = 1.1.1
* scalaVersion in ThisBuild := "2.12.3"
* Oracle Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
* Ubuntu 16.04 x64
* addSbtPlugin("com.sksamuel.scapegoat" %% "sbt-scapegoat" % "1.0.9")
* scapegoatVersion in ThisBuild := "1.3.4"

Running commands `sbt scapegoat` or `sbt "project module1" scapegoat` results in error:
```
[error] java.lang.IncompatibleClassChangeError: vtable stub
[error]         at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:488)
[error]         at java.lang.StringBuilder.append(StringBuilder.java:166)
[error]         at com.sksamuel.scapegoat.inspections.imports.DuplicateImport$$anon$2$$anon$1.$anonfun$inspect$1(DuplicateImport.scala:28)
[error]         at com.sksamuel.scapegoat.inspections.imports.DuplicateImport$$anon$2$$anon$1.$anonfun$inspect$1$adapted(DuplicateImport.scala:27)
[error]         at scala.collection.immutable.List.foreach(List.scala:389)
[error]         at com.sksamuel.scapegoat.inspections.imports.DuplicateImport$$anon$2$$anon$1.inspect(DuplicateImport.scala:27)
[error]         at com.sksamuel.scapegoat.InspectionContext$Traverser.traverse(Inspection.scala:94)
[error]         at com.sksamuel.scapegoat.InspectionContext$Traverser.traverse$(Inspection.scala:82)
[error]         at com.sksamuel.scapegoat.inspections.imports.DuplicateImport$$anon$2$$anon$1.traverse(DuplicateImport.scala:14)
[error]         at com.sksamuel.scapegoat.inspections.imports.DuplicateImport$$anon$2$$anon$1.traverse(DuplicateImport.scala:14)
[error]         at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$2(Trees.scala:2498)
[error]         at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2507)
[error]         at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$1(Trees.scala:2498)
[error]         at scala.reflect.api.Trees$Traverser.traverseStats(Trees.scala:2497)
[error]         at scala.reflect.internal.Trees.itraverse(Trees.scala:1337)
[error]         at scala.reflect.internal.Trees.itraverse$(Trees.scala:1211)
[error]         at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[error]         at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:16)
[error]         at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2475)
[error]         at com.sksamuel.scapegoat.inspections.imports.DuplicateImport$$anon$2$$anon$1.com$sksamuel$scapegoat$InspectionContext$Traverser$$super$traverse(DuplicateImport.scala:14)
[error]         at com.sksamuel.scapegoat.InspectionContext$Traverser.continue(Inspection.scala:78)
[error]         at com.sksamuel.scapegoat.InspectionContext$Traverser.continue$(Inspection.scala:78)
[error]         at com.sksamuel.scapegoat.inspections.imports.DuplicateImport$$anon$2$$anon$1.continue(DuplicateImport.scala:14)
[error]         at com.sksamuel.scapegoat.inspections.imports.DuplicateImport$$anon$2$$anon$1.inspect(DuplicateImport.scala:21)
[error]         at com.sksamuel.scapegoat.InspectionContext$Traverser.traverse(Inspection.scala:94)
[error]         at com.sksamuel.scapegoat.InspectionContext$Traverser.traverse$(Inspection.scala:82)
[error]         at com.sksamuel.scapegoat.inspections.imports.DuplicateImport$$anon$2$$anon$1.traverse(DuplicateImport.scala:14)
[error]         at com.sksamuel.scapegoat.ScapegoatComponent$Transformer.$anonfun$transform$3(plugin.scala:203)
[error]         at com.sksamuel.scapegoat.ScapegoatComponent$Transformer.$anonfun$transform$3$adapted(plugin.scala:202)
[error]         at scala.Option.foreach(Option.scala:257)
[error]         at com.sksamuel.scapegoat.ScapegoatComponent$Transformer.$anonfun$transform$2(plugin.scala:202)
[error]         at com.sksamuel.scapegoat.ScapegoatComponent$Transformer.$anonfun$transform$2$adapted(plugin.scala:200)
[error]         at scala.collection.immutable.List.foreach(List.scala:389)
[error]         at com.sksamuel.scapegoat.ScapegoatComponent$Transformer.transform(plugin.scala:200)
[error]         at com.sksamuel.scapegoat.ScapegoatComponent$Transformer.transform(plugin.scala:189)
[error]         at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:140)
[error]         at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
[error]         at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:426)
[error]         at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:419)
[error]         at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1(Global.scala:390)
[error]         at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted(Global.scala:390)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:929)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:929)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[error]         at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:390)
[error]         at com.sksamuel.scapegoat.ScapegoatComponent$$anon$1.run(plugin.scala:155)
[error]         at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1431)
[error]         at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1416)
[error]         at scala.tools.nsc.Global$Run.compileSources(Global.scala:1412)
[error]         at scala.tools.nsc.Global$Run.compile(Global.scala:1515)
[error]         at xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
[error]         at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
[error]         at xsbt.CompilerInterface.run(CompilerInterface.scala:31)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:83)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:134)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:74)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:117)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:305)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:305)
[error]         at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:101)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:82)
[error]         at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:110)
[error]         at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:57)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:84)
[error]         at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:129)
[error]         at sbt.internal.inc.Incremental$.compile(Incremental.scala:75)
[error]         at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:61)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:309)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:267)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:158)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:237)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:68)
[error]         at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1429)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1403)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:271)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
```

**Comment by antoon-r** [comment]
Works fine with scapegoatVersion in ThisBuild := "1.3.3"
